name: "Azure Blob Storage Download"
author: "Ymoona"
description: "Downloads a file from Azure Blob Storage"
branding:
  icon: "box"
  color: "green"
inputs:
  connection_string:
    description: "The connection string for the storage account."
    required: true
  container_name:
    description: "The name of the storage account container a file will be uploaded to"
    required: true
  file: 
    description: "The name of the file to download"
    required: true
  source_dir:
    descripton: "The source directory"
    required: true/
  
runs:
  using: "docker"
  image: "Dockerfile"
